draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  key_rx: 6.0
  key_ry: 6.0
  n_columns: 1
  dark_mode: auto
  svg_extra_style: |
    svg.keymap {
      font-family: Ubuntu Mono, Inconsolata, Consolas, monospace;
      font-size: 12px;
      font-weight: bold;
    }

parse_config:
  raw_binding_map:
    "&bootloader": "BOOT"
    "&caps_word": "⇪\nWORD"
  zmk_keycode_map:
    LGUI: "⌘"
    RGUI: "⌘"
    LALT: "⌥"
    RALT: "⌥"
    LSHFT: "⇧"
    RSHFT: "⇧"
    LCTRL: "⌃"
    RCTRL: "⌃"
    LCLCK: "⇪"
    TAB: "⇥"
    BSPC: "⌫"
    DEL: "⌦"
    RET: "↩"
    ESC: "⎋"
    C_VOL_UP: "♪+"
    C_VOL_DN: "♪-"
    C_MUTE: "♪✕"
    C_PP: "▶/‖"
    C_NEXT: ">>"
    C_PREV: "<<"
