draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  key_rx: 6.0
  key_ry: 6.0
  n_columns: 1
  dark_mode: auto
  svg_extra_style: |
    svg.keymap {
      font-family: Ubuntu Mono, Inconsolata, Consolas, monospace;
      font-size: 14px;
      font-weight: bold;
    }

parse_config:
  raw_binding_map:
    "&bootloader": "BOOT"
    "&caps_word": "⇪\nWORD"
    "&euro": "€"
    "&zoom_in": "Zoom+"
    "&zoom_out": "Zoom-"
  zmk_keycode_map:
    # Modificateurs
    LGUI: "⌘"
    RGUI: "⌘"
    LALT: "⌥"
    RALT: "⌥"
    LSHFT: "⇧"
    RSHFT: "⇧"
    LCTRL: "⌃"
    RCTRL: "⌃"
    # Touches spéciales
    TAB: "⇥"
    BSPC: "⌫"
    DEL: "⌦"
    RET: "↩"
    ESC: "⎋"
    CLCK: "⇪"
    PSCRN: "⎙"
    INS: "Ins"
    # Navigation
    LEFT: "←"
    RIGHT: "→"
    UP: "↑"
    DOWN: "↓"
    PG_UP: "PgUp"
    PG_DN: "PgDn"
    HOME: "⇱"
    END: "⇲"
    # Raccourcis
    K_UNDO: "↩"
    K_CUT: "✂"
    K_COPY: "⎘"
    K_PASTE: "⎗"
    # Média
    C_VOL_UP: "♪+"
    C_VOL_DN: "♪-"
    C_MUTE: "♪✕"
    C_PP: "⏯"
    C_NEXT: "⏭"
    C_PREV: "⏮"
    # Ponctuation et symboles
    FSLH: "/"
    MINUS: "-"
    PLUS: "+"
    EQUAL: "="
    UNDER: "_"
    BSLH: "\\"
    PIPE: "|"
    TILDE: "~"
    GRAVE: "`"
    EXCL: "!"
    AT: "@"
    HASH: "#"
    DLLR: "$"
    PRCNT: "%"
    CARET: "^"
    AMPS: "&"
    ASTRK: "*"
    LPAR: "("
    RPAR: ")"
    LBKT: "["
    RBKT: "]"
    LBRC: "{"
    RBRC: "}"
    LT: "<"
    GT: ">"
    SEMI: ";"
    COLON: ":"
    SQT: "'"
    DQT: "\""
    COMMA: ","
    DOT: "."
    QMARK: "?"
    # Bluetooth
    BT_CLR: "BT\nClr"
